Improve Reweights
pharmaR/risk_assessment pull request #224
Opened 2022-03-22 18:51 UTC by Jeff-Thompson12

PR for continued improvements to #208. Addresses issue #222 as well.

2022-03-24 13:41 UTC, AARON-CLARK commented
Is this one ready for review too @Jeff-Thompson12 ?

2022-03-24 13:47 UTC, Jeff-Thompson12 commented
@AARON-CLARK it addresses both items you noted in #220, but you did say it was not a comprehensive list. So I was looking for what other improvements are needed. Those could be handled in a separate PR though.

It makes sense to go ahead and review it so that those changes can be implemented before our meeting.

2022-03-24 15:22 UTC, AARON-CLARK requested changes
Hi @Jeff-Thompson12, I don't think this has to be completed by our meeting today, so I'll request changes. Couple of things I noticed:

(1) First, the whole re-weighting "module" should be moved to the Admin tools tab. So, it may be appropriate to just make a tabsetPanel, one tabPanel for the "credential manager" and another tabPanel for the "assessment criteria"?

(2) Are you getting double column sorter icon's on the table like me? It looks like they didn't exist when I took the screenshot in issue #220. See image below:
![image](https://user-images.githubusercontent.com/17878953/159948931-31997548-2e5a-4f93-a15a-75e945c7e643.png)

(3) It looks like if you submit a final decision for package, then change the weights and re-calc risk scores, the currently selected package decision doesn't get reverted/ undone until you toggle the selected package in the sidebar (to anything) and then re-select the previous package that formerly had a decision made. Can package decision be more reactive in this context?

2022-03-25 18:04 UTC, Jeff-Thompson12 commented
@AARON-CLARK this is ready for you to take another look.

2022-03-28 13:51 UTC, AARON-CLARK commented
Hi @Jeff-Thompson12, there are some conflicts on this branch now.

2022-03-28 14:06 UTC, AARON-CLARK requested changes
@Jeff-Thompson12, looks great! However, I set a package's risk to 'medium' and then re-calculated risk scores and the slider went back down to 'low' on the sidebar. After thinking about it more this morning, I don't really care about maintaining that slider's previous value, so I would just forget about it unless you really want to fix it. Instead, I have a few small aesthetic requests:

I think it's slightly hard to see both of these tabs (pictured below) since they are spanning the whole screen. And the bootstrap theme we chose doesn't help since makes them both white (even when one is selected... usually the shading changes when selected). Do you think you could make the tabs the approximate size of the text string. Also add just a little margin between the title and the start of the tabs. Maybe just one or two `br()`s.

![image](https://user-images.githubusercontent.com/17878953/160412972-5cbb5fd9-64f4-4399-bb1d-c5b325c6666e.png)

Second, the message/note at the bottom of the metric re-weighting needs some margin around it too. Maybe a couple more `br()`s and put some padding on the left-hand side if you think it looks good.

![image](https://user-images.githubusercontent.com/17878953/160413879-f7a18bbf-414e-43c6-966d-d31bb1248882.png)

Is it possible to have the name of the package show up on the second line? I did this for package upload tab's pop-up and I think it looks really good!

![image](https://user-images.githubusercontent.com/17878953/160414807-647dbdd5-a6a0-4c67-a014-a6b28b570b91.png)

2022-03-28 14:42 UTC, Jeff-Thompson12 commented
@AARON-CLARK the packages are not on the second line for me in the package upload. The `\n` characters seem to be getting ignored in `withProgress` but I will look into it more.

2022-03-28 14:52 UTC, AARON-CLARK commented
> @AARON-CLARK the packages are not on the second line for me in the package upload. The `\n` characters seem to be getting ignored in `withProgress` but I will look into it more.

Ya, I think I noticed that too, so I just made the pop-up box smaller, constrained to a certain number of pixels. But it sounds like that's not working for you! lol shoot. Let me know what you find.

2022-03-28 15:53 UTC, Jeff-Thompson12 commented
@AARON-CLARK you can't manually add the break in the text itself because the progress message and details are spans. I just added a little JS to add a <br> HTML element after the progress message within the withProgress.

2022-03-28 15:54 UTC, Jeff-Thompson12 commented
@AARON-CLARK this PR is ready for you to take another look

2022-03-28 18:26 UTC, AARON-CLARK commented on R/reweightView.R
>                )
line 113?

2022-03-28 18:28 UTC, AARON-CLARK commented
Hi @Jeff-Thompson12, not trying to be knit-picky, but now my message is text wrapping, then displaying the package name. Is this happening for you? If you're good with it then I'm good with it.

2022-03-28 18:34 UTC, Jeff-Thompson12 commented
> Hi @Jeff-Thompson12, not trying to be knit-picky, but now my message is text wrapping, then displaying the package name. Is this happening for you? If you're good with it then I'm good with it.
> 
> ![image](https://user-images.githubusercontent.com/17878953/160462954-a7bdc9aa-3e81-4d24-98f5-bbb42494c083.png)

The message for the progress notification was always wrapping for me.

2022-03-28 19:26 UTC, AARON-CLARK commented on R/reweightView.R
>                )
@Jeff-Thompson12, correct. I see you put some `br()`s before the note, but I don't think those were necessary (unless you like them there). I was only envisioning added margin after the note. Thanks!

2022-03-28 20:50 UTC, Jeff-Thompson12 commented
@AARON-CLARK I used jQuery to adjust the width of the `shiny-notification` and added padding beneath the notice.

2022-03-28 21:24 UTC, AARON-CLARK approved these changes
beautiful!

2022-03-28 21:24 UTC, merged